version: '3.8'

services:

  db:
    image: postgres:15
    container_name: rockpulse_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGREST_HOST: db
      POSTGRES_HOST_AUTH_METHOD: md5 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"   # Host 5434 -> Container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    
    networks:
      - rocknet

  backend:
    build: .
    container_name: rockpulse_backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL : "postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
      DB_HOST: "db"
      DB_PORT: "${DB_PORT}"
      IMAGE_DIR: "/app/images"
      OUTPUT_DIR: "/app/outputs"
      MODEL_PATH: "/app/model/${MODEL_NAME}"
      BACKEND: "true"
    volumes:
      - ./images:/app/images       # Input images
      - ./outputs:/app/outputs     # Processed output images (annotated PNGs)
      - ./model:/app/model           # ONNX model files
      - ./logs:/app/logs             # Logs from the backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10 
    
    networks:
      - rocknet

networks:
  rocknet:
    driver: bridge

volumes:
  postgres_data:
